{{- if .Values.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ include "name" . }}
        controlledResources:
          - cpu
          - memory
        {{- with .Values.verticalPodAutoscaler.containerPolicies.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.verticalPodAutoscaler.containerPolicies.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "resource.default.name" . }}
  updatePolicy:
    updateMode: Auto
{{- end }}

