apiVersion: v2
appVersion: 0.1.4
name: teleport-exporter
description: A Helm chart for teleport-exporter, which exposes Prometheus metrics about nodes, clusters, databases, and applications registered in Teleport.
type: application
home: https://github.com/giantswarm/teleport-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 0.1.4
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
