apiVersion: v2
appVersion: 0.1.0
name: teleport-exporter
description: A Helm chart for teleport-exporter, which exposes Prometheus metrics about nodes, clusters, databases, and applications registered in Teleport.
type: application
home: https://github.com/giantswarm/teleport-exporter
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 0.1.0
annotations:
  application.giantswarm.io/team: "shield"
  config.giantswarm.io/version: 1.x.x
